### PR TITLE
WIP: Type hints

### PR DESCRIPTION
**Pull request by Anton-4**
- I added:
  + type hints
  + nox to travis to automatically check the type hints
  + support for python3.7 and removed support for python2.6

- Forget the commits about graphml, those need to be on a different branch.
  I removed the corresponding files for that.
- Pull request is still work-in-progress because I need to add type-hints to acii_canvas as well for
  a successful run on travis.

### CODE REVIEW

**Comment by PaulSchweizer** [comment]
@Anton-4 , thanks for the work on this! Is there a way we can keep support for Python2.6? I know some people who run flowpipe in a py2.6 environment ...

**Comment by Anton-4** [comment]
It is possible to keep supporting python2.6 but it seems better not to.
Official support for python2.6 ended in [2013](https://mail.python.org/pipermail/python-dev/2013-September/128287.html). Thanks to versioning** on pypi those who need to use python2.6 can still do so except they will not get new features.

**For this to be true I believe ascii_canvas needs to be deployed to pypi, so I will keep python2.6 for now until we have a flowpipe release that gets ascii_canvas from pypi.

**Comment by PaulSchweizer** [comment]
ascii canvas is up on pypi now @Anton-4 https://pypi.org/project/ascii-canvas/ Thanks again for getting this started! 
Ok, then let's keep py2.6 in there for the moment, I mean if it passes the tests and we have users on py2.6 (almost unbelievable, but it is true :D ) why not keep it there, right? Or do you see any concerns other than the fact that nobody should be using it anymore since support has ended?

**Comment by Anton-4** [comment]
When we want to use other libraries it is very likely they will not support 2.6 so we would not be able to use them. Until that happens we can keep support for 2.6 .

**Comment by neuneck** [comment]
The last activity on this PR is almost 5 years old.
@Anton-4 Are you still around? Do you want to continue this / update it to match all the changes in the repo?
If not, I think we ought to consider closing the PR.

**Pull request closed without merging**
