### PR TITLE
Rewrote evaluation matrix computation iteratively

### PR DESCRIPTION
**Pull request by neuneck**
Since I had this mapped out in my head already, I went ahead and made the evaluation matrix computation iterative.

### CODE REVIEW

**Review by PaulSchweizer — APPROVED** [review]
Nice! Thank you!

**Comment by neuneck** [comment]
@PaulSchweizer Before I merge, did you run it against the situation that triggered your performance improvements? I'm not a computer scientist, and while getting rid of the tail recursion is nice, I don't know how to judge the runtime of recursive code (my code is O(n^3) in the number of nodes in the graph, with a worst case of a non-branching chain of nodes).

**Comment by PaulSchweizer** [comment]
The case I encountered is very hard to reproduce at this point unfortunately as the code has moved on since then and is very involved to test in the first place. Have you compared execution times to what it was before your change? Definitely the previous change I made solved our issue, bringing eval time down from minutes (!) to a negligible milliseconds.

**Comment by neuneck** [comment]
I found an algorithm for generating a topological sort of a DAG in linear time and adapted it to yield the evaluation matrix. I'm confident this can be merged without slowing things down, but please take another look.

**Comment by PaulSchweizer** [comment]
Very neat, thanks for diving deeper into this! I'll think we can merge this.

**Pull request merged**
